from __future__ import annotations

from typing import Any


INTELLIGENCE_FEATURES: list[dict[str, Any]] = [
    {
        "key": "intelligence_demo",
        "label": "Modo demo AI predictivo",
        "category": "demo",
        "description": "Previews limitados de predicciones y recomendaciones sin activar funciones premium completas.",
        "demo_allowed": True,
        "default_quota_monthly": 50,
    },
    {
        "key": "ai_premium",
        "label": "AI Premium",
        "category": "licensing",
        "description": "Licencia paraguas para capacidades avanzadas de inteligencia y agents enterprise.",
        "demo_allowed": False,
        "default_quota_monthly": 0,
    },
    {
        "key": "ml_predictions",
        "label": "Predicciones ML",
        "category": "machine_learning",
        "description": "Capa general para scoring, optimizacion y prediccion multi-tenant.",
        "demo_allowed": True,
        "default_quota_monthly": 500,
    },
    {
        "key": "lead_scoring_ml",
        "label": "Lead scoring predictivo",
        "category": "machine_learning",
        "description": "Scoring de leads y temperatura comercial basado en CRM, mensajes y engagement.",
        "demo_allowed": True,
        "default_quota_monthly": 500,
    },
    {
        "key": "churn_prediction",
        "label": "Churn prediction",
        "category": "machine_learning",
        "description": "Riesgo de abandono por inactividad, baja respuesta y degradacion de engagement.",
        "demo_allowed": True,
        "default_quota_monthly": 300,
    },
    {
        "key": "smart_remarketing",
        "label": "Smart remarketing",
        "category": "optimization",
        "description": "Recomendaciones de canal, horario, frecuencia y segmento para reactivacion.",
        "demo_allowed": True,
        "default_quota_monthly": 300,
    },
    {
        "key": "ai_operational_intelligence",
        "label": "AI operational intelligence",
        "category": "operations",
        "description": "Anomalias de webhooks, colas, proveedores AI, Meta y riesgo operativo por tenant.",
        "demo_allowed": True,
        "default_quota_monthly": 300,
    },
    {
        "key": "predictive_recommendations",
        "label": "Recomendaciones predictivas",
        "category": "advisor",
        "description": "Recomendaciones accionables para Advisor y operaciones comerciales.",
        "demo_allowed": True,
        "default_quota_monthly": 300,
    },
    {
        "key": "advanced_analytics",
        "label": "Advanced analytics",
        "category": "analytics",
        "description": "Analitica avanzada y reporting predictivo sobre CRM, canales, triggers y campanas.",
        "demo_allowed": True,
        "default_quota_monthly": 0,
    },
    {
        "key": "ai_advisors_premium",
        "label": "AI Advisors premium",
        "category": "advisor",
        "description": "Advisor con contexto ML, recomendaciones ejecutivas y diagnostico predictivo.",
        "demo_allowed": True,
        "default_quota_monthly": 300,
    },
    {
        "key": "autonomous_operations",
        "label": "Autonomous operations",
        "category": "operations",
        "description": "Centro autonomo para detectar anomalias, priorizar riesgos y coordinar optimizaciones con supervision humana.",
        "demo_allowed": True,
        "default_quota_monthly": 300,
    },
    {
        "key": "ai_self_healing",
        "label": "AI self-healing",
        "category": "operations",
        "description": "Playbooks de remediacion controlada para webhooks, colas, tokens, Meta y degradacion operativa.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "ai_control_center",
        "label": "AI Control Center",
        "category": "governance",
        "description": "Politicas tenant-level de autonomia, sensibilidad, aprobaciones y limites de acciones AI.",
        "demo_allowed": True,
        "default_quota_monthly": 0,
    },
    {
        "key": "ai_marketplace",
        "label": "AI Marketplace",
        "category": "ecosystem",
        "description": "Marketplace interno de agentes, AI packs, playbooks, workflows y automatizaciones instalables por tenant.",
        "demo_allowed": True,
        "default_quota_monthly": 100,
    },
    {
        "key": "ai_plugin_center",
        "label": "AI Plugin Center",
        "category": "ecosystem",
        "description": "Registro tenant-level de plugins AI/CRM/workflow con permisos, sandbox metadata-only y ciclo de vida controlado.",
        "demo_allowed": True,
        "default_quota_monthly": 100,
    },
    {
        "key": "ai_developer_console",
        "label": "AI Developer Console",
        "category": "developer",
        "description": "Consola de SDK, apps developer, webhooks, scopes y manifests para extender Scentra de forma gobernada.",
        "demo_allowed": True,
        "default_quota_monthly": 100,
    },
    {
        "key": "ai_tool_registry",
        "label": "AI Tool Registry",
        "category": "governance",
        "description": "Registry central de herramientas AI disponibles para agentes, plugins, workflows y copilotos.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "ai_app_framework",
        "label": "AI App Framework",
        "category": "ecosystem",
        "description": "Framework para mini AI apps, dashboards operacionales y copilotos tenant-level.",
        "demo_allowed": True,
        "default_quota_monthly": 100,
    },
    {
        "key": "enterprise_ai_network",
        "label": "Enterprise AI Network",
        "category": "enterprise_network",
        "description": "Red de inteligencia empresarial con agregados anonimizados, benchmarking y aprendizaje vertical seguro.",
        "demo_allowed": True,
        "default_quota_monthly": 100,
    },
    {
        "key": "vertical_ai_intelligence",
        "label": "Vertical AI Intelligence",
        "category": "enterprise_network",
        "description": "Insights, KPIs, advisors y recomendaciones especializados por industria.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "industry_ai_models",
        "label": "Industry AI Models",
        "category": "machine_learning",
        "description": "Routing y gobierno de modelos/pipelines especializados por vertical sin entrenamiento LLM pesado.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "benchmark_intelligence",
        "label": "Benchmark Intelligence",
        "category": "analytics",
        "description": "Benchmarks empresariales contra agregados anonimizados de la industria.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "cross_tenant_intelligence",
        "label": "Cross-tenant anonymized intelligence",
        "category": "privacy",
        "description": "Agregacion estadistica privacy-safe entre tenants, sin mensajes crudos ni datos privados.",
        "demo_allowed": True,
        "default_quota_monthly": 100,
    },
    {
        "key": "vertical_ai_advisors",
        "label": "Vertical AI Advisors",
        "category": "advisor",
        "description": "Copilotos especializados por industria con KPIs, playbooks y recomendaciones sectoriales.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "ai_playbook_library",
        "label": "AI Playbook Library",
        "category": "enterprise_network",
        "description": "Biblioteca de playbooks, triggers y workflows verticales recomendados sin activacion automatica.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "federated_learning",
        "label": "Federated Learning",
        "category": "federated_learning",
        "description": "Control-plane federado con opt-in tenant, paquetes locales agregados y aprendizaje global sin compartir datos crudos.",
        "demo_allowed": True,
        "default_quota_monthly": 120,
    },
    {
        "key": "federated_model_updates",
        "label": "Federated model updates",
        "category": "federated_learning",
        "description": "Permite enviar paquetes estadisticos tenant-scoped a rondas federadas privacy-safe.",
        "demo_allowed": True,
        "default_quota_monthly": 120,
    },
    {
        "key": "privacy_safe_model_aggregation",
        "label": "Privacy-safe model aggregation",
        "category": "federated_learning",
        "description": "Agregacion ponderada con thresholds de cohorte, trazabilidad y sin promocion automatica de modelos.",
        "demo_allowed": True,
        "default_quota_monthly": 80,
    },
    {
        "key": "global_intelligence",
        "label": "Global Intelligence",
        "category": "federated_learning",
        "description": "Senales globales y benchmarks agregados por industria sin mensajes, nombres o conversaciones de otros tenants.",
        "demo_allowed": True,
        "default_quota_monthly": 100,
    },
    {
        "key": "federated_benchmarking",
        "label": "Federated benchmarking",
        "category": "federated_learning",
        "description": "Comparacion y aprendizaje por cohorte usando paquetes federados anonimizados y minima muestra.",
        "demo_allowed": True,
        "default_quota_monthly": 100,
    },
    {
        "key": "ai_workflow_composer",
        "label": "AI Workflow Composer",
        "category": "workflow_composer",
        "description": "Diseno, simulacion, aprobacion, versionado y activacion controlada de workflows AI.",
        "demo_allowed": True,
        "default_quota_monthly": 150,
    },
    {
        "key": "workflow_composer_templates",
        "label": "Workflow Composer Templates",
        "category": "workflow_composer",
        "description": "Plantillas AI seguras para crear workflows, playbooks y handoffs sin efectos automaticos.",
        "demo_allowed": True,
        "default_quota_monthly": 250,
    },
    {
        "key": "ai_trust_center",
        "label": "AI Trust Center",
        "category": "trust_governance",
        "description": "Centro tenant-level de confianza, politicas, riesgos, incidentes, auditoria y compliance AI.",
        "demo_allowed": True,
        "default_quota_monthly": 100,
    },
    {
        "key": "ai_governance_policies",
        "label": "AI Governance Policies",
        "category": "trust_governance",
        "description": "Politicas de aprobacion, privacidad, rollout, herramientas y controles AI por tenant.",
        "demo_allowed": True,
        "default_quota_monthly": 100,
    },
    {
        "key": "ai_risk_assessments",
        "label": "AI Risk Assessments",
        "category": "trust_governance",
        "description": "Evaluacion auditable de riesgos en agentes, workflows, modelos, plugins y acciones autonomas.",
        "demo_allowed": True,
        "default_quota_monthly": 100,
    },
    {
        "key": "ai_model_cards",
        "label": "AI Model Cards",
        "category": "model_governance",
        "description": "Documentacion viva de uso previsto, datos, evaluacion, rollout y limites de modelos AI/ML.",
        "demo_allowed": True,
        "default_quota_monthly": 100,
    },
    {
        "key": "ai_compliance_reports",
        "label": "AI Compliance Reports",
        "category": "compliance",
        "description": "Reportes ejecutivos de confianza, controles, riesgos abiertos, incidentes y evidencia AI.",
        "demo_allowed": True,
        "default_quota_monthly": 50,
    },
    {
        "key": "ai_audit_exports",
        "label": "AI Audit Exports",
        "category": "compliance",
        "description": "Auditoria exportable y trazabilidad de decisiones, politicas y revisiones AI.",
        "demo_allowed": True,
        "default_quota_monthly": 50,
    },
    {
        "key": "realtime_intelligence_layer",
        "label": "AI Real-Time Intelligence Layer",
        "category": "real_time",
        "description": "Centro live tenant-level sobre eventos, predicciones, recomendaciones, anomalias y salud AI.",
        "demo_allowed": True,
        "default_quota_monthly": 300,
    },
    {
        "key": "realtime_event_stream",
        "label": "Real-time event stream",
        "category": "real_time",
        "description": "Feed SSE/polling con sesiones, cursores y snapshots live sin dependencia externa de streaming.",
        "demo_allowed": True,
        "default_quota_monthly": 300,
    },
    {
        "key": "realtime_ai_alerts",
        "label": "Real-time AI alerts",
        "category": "real_time",
        "description": "Alertas live derivadas de recomendaciones, predicciones, anomalias operativas e incidentes AI.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "realtime_intelligence_dashboard",
        "label": "Real-time Intelligence Dashboard",
        "category": "real_time",
        "description": "Dashboard live para Inbox, CRM, operaciones, ModelOps y Advisor con refresco seguro.",
        "demo_allowed": True,
        "default_quota_monthly": 300,
    },
    {
        "key": "voice_intelligence",
        "label": "Voice Intelligence",
        "category": "voice_multimodal",
        "description": "Analisis de notas de voz con transcripcion, resumen, sentimiento, intencion y recomendaciones de seguimiento.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "voice_transcription",
        "label": "Voice transcription",
        "category": "voice_multimodal",
        "description": "Transcripcion controlada de audios del Inbox sin guardar media cruda fuera del almacenamiento existente.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "voice_sentiment_intent",
        "label": "Voice sentiment and intent",
        "category": "voice_multimodal",
        "description": "Clasificacion de sentimiento, urgencia e intencion comercial a partir de audios.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "vision_intelligence",
        "label": "Vision Intelligence",
        "category": "voice_multimodal",
        "description": "Analisis de imagenes y documentos del Inbox con descripcion, OCR, resumen e intencion.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "image_understanding",
        "label": "Image understanding",
        "category": "voice_multimodal",
        "description": "Descripcion y clasificacion de imagenes recibidas por canales conversacionales.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "document_ocr",
        "label": "Document OCR",
        "category": "voice_multimodal",
        "description": "Extraccion controlada de texto y resumen de documentos enviados en conversaciones.",
        "demo_allowed": True,
        "default_quota_monthly": 150,
    },
    {
        "key": "web_search_intelligence",
        "label": "Web Search Intelligence",
        "category": "voice_multimodal",
        "description": "Busqueda web tenant-scoped con fuentes, trazabilidad y aprobacion humana antes de uso externo.",
        "demo_allowed": True,
        "default_quota_monthly": 120,
    },
    {
        "key": "image_search_intelligence",
        "label": "Image Search Intelligence",
        "category": "voice_multimodal",
        "description": "Busqueda de imagenes de referencia con metadatos de fuente/licencia y approval layer humano.",
        "demo_allowed": True,
        "default_quota_monthly": 100,
    },
    {
        "key": "external_source_assist",
        "label": "External Source Assist",
        "category": "voice_multimodal",
        "description": "Asistencia con fuentes externas para agentes y humanos sin ejecutar envios automaticos.",
        "demo_allowed": True,
        "default_quota_monthly": 120,
    },
    {
        "key": "agent_multimodal_tools",
        "label": "Agent Multimodal Tools",
        "category": "voice_multimodal",
        "description": "Herramientas multimodales para agentes con trazabilidad, limites, demo mode y sin envio automatico a clientes.",
        "demo_allowed": True,
        "default_quota_monthly": 120,
    },
    {
        "key": "agent_voice_tools",
        "label": "Agent Voice Tools",
        "category": "voice_multimodal",
        "description": "Permite a agentes solicitar analisis de audios existentes del Inbox y usar el resultado como contexto gobernado.",
        "demo_allowed": True,
        "default_quota_monthly": 120,
    },
    {
        "key": "agent_vision_tools",
        "label": "Agent Vision Tools",
        "category": "voice_multimodal",
        "description": "Permite a agentes solicitar analisis de imagenes/documentos existentes del Inbox y usar el resultado como contexto gobernado.",
        "demo_allowed": True,
        "default_quota_monthly": 120,
    },
    {
        "key": "agent_external_search_tools",
        "label": "Agent External Search Tools",
        "category": "voice_multimodal",
        "description": "Permite a agentes ejecutar busqueda web/imagen con fuentes y aprobacion humana por resultado.",
        "demo_allowed": True,
        "default_quota_monthly": 80,
    },
    {
        "key": "multimodal_memory_events",
        "label": "Multimodal Memory Events",
        "category": "voice_multimodal",
        "description": "Destila resultados de voz, vision, busqueda y herramientas de agentes en eventos seguros para memoria, ML y RAG.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "multimodal_training_events",
        "label": "Multimodal Training Events",
        "category": "machine_learning",
        "description": "Guarda senales multimodales limpias como features y eventos de entrenamiento sin entrenar modelos automaticamente.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "multimodal_rag_materialization",
        "label": "Multimodal RAG Materialization",
        "category": "voice_multimodal",
        "description": "Permite materializar eventos multimodales revisados como fuentes RAG tenant-scoped.",
        "demo_allowed": True,
        "default_quota_monthly": 120,
    },
    {
        "key": "multimodal_agent_memory",
        "label": "Multimodal Agent Memory",
        "category": "voice_multimodal",
        "description": "Permite convertir senales multimodales revisadas en memoria usable por agentes.",
        "demo_allowed": True,
        "default_quota_monthly": 120,
    },
    {
        "key": "multimodal_observability",
        "label": "Multimodal Observability",
        "category": "voice_multimodal",
        "description": "Observabilidad de voz, vision, busqueda e instrumentos de agente: costo, latencia, errores, calidad y fuentes usadas.",
        "demo_allowed": True,
        "default_quota_monthly": 120,
    },
    {
        "key": "multimodal_cost_observability",
        "label": "Multimodal Cost Observability",
        "category": "voice_multimodal",
        "description": "Costeo estimado por media/proveedor usando politicas Admin de precios y uso real de AI Gateway/Search.",
        "demo_allowed": True,
        "default_quota_monthly": 120,
    },
    {
        "key": "multimodal_quality_monitoring",
        "label": "Multimodal Quality Monitoring",
        "category": "voice_multimodal",
        "description": "Monitoreo de confianza, aprobacion de fuentes, errores y senales de calidad de resultados multimodales.",
        "demo_allowed": True,
        "default_quota_monthly": 120,
    },
    {
        "key": "multimodal_safe_rollout",
        "label": "Multimodal Safe Rollout",
        "category": "voice_multimodal",
        "description": "Control seguro de activacion por policy para modo off, demo, canary y full sin romper el runtime existente.",
        "demo_allowed": True,
        "default_quota_monthly": 0,
    },
    {
        "key": "multimodal_canary",
        "label": "Multimodal Canary",
        "category": "voice_multimodal",
        "description": "Asignacion canary deterministica para habilitar voz, vision y busqueda por porcentaje con fallback demo.",
        "demo_allowed": True,
        "default_quota_monthly": 0,
    },
    {
        "key": "autonomous_revenue_engine",
        "label": "Autonomous Revenue Engine",
        "category": "revenue_intelligence",
        "description": "Motor supervisado para detectar oportunidades comerciales, priorizar follow-ups y recomendar acciones de revenue sin ejecutar mensajes ni cobros automaticamente.",
        "demo_allowed": True,
        "default_quota_monthly": 120,
    },
    {
        "key": "revenue_opportunity_detection",
        "label": "Revenue opportunity detection",
        "category": "revenue_intelligence",
        "description": "Deteccion de leads calientes, recuperacion, upsell y oportunidades de cierre desde CRM, conversaciones y eventos.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "revenue_forecasting",
        "label": "Revenue forecasting",
        "category": "revenue_intelligence",
        "description": "Forecast operativo basado en oportunidades y pipeline disponible; no reemplaza facturacion legal.",
        "demo_allowed": True,
        "default_quota_monthly": 80,
    },
    {
        "key": "revenue_playbooks",
        "label": "Revenue playbooks",
        "category": "revenue_intelligence",
        "description": "Playbooks sugeridos para recuperacion, cierre, upsell y reactivacion con aprobacion humana.",
        "demo_allowed": True,
        "default_quota_monthly": 120,
    },
    {
        "key": "revenue_experiments",
        "label": "Revenue experiments",
        "category": "revenue_intelligence",
        "description": "Experimentos A/B o hipotesis comerciales gobernadas para mejorar conversion sin activar campanas automaticamente.",
        "demo_allowed": True,
        "default_quota_monthly": 80,
    },
    {
        "key": "enterprise_memory_network",
        "label": "AI Enterprise Memory Network",
        "category": "enterprise_memory",
        "description": "Red de memoria empresarial tenant-scoped para agentes, RAG y aprendizaje organizacional con revision y privacidad.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "memory_graph",
        "label": "Memory graph",
        "category": "enterprise_memory",
        "description": "Grafo de memorias, relaciones y fuentes internas para recuperacion contextual segura.",
        "demo_allowed": True,
        "default_quota_monthly": 200,
    },
    {
        "key": "memory_governance",
        "label": "Memory governance",
        "category": "enterprise_memory",
        "description": "Politicas de retencion, revision, sensibilidad y aprobacion para memoria empresarial.",
        "demo_allowed": True,
        "default_quota_monthly": 120,
    },
    {
        "key": "cross_agent_memory_routing",
        "label": "Cross-agent memory routing",
        "category": "enterprise_memory",
        "description": "Routing de memoria entre agentes del mismo tenant sin exponer datos entre tenants.",
        "demo_allowed": True,
        "default_quota_monthly": 160,
    },
    {
        "key": "memory_quality_scoring",
        "label": "Memory quality scoring",
        "category": "enterprise_memory",
        "description": "Scoring de calidad, confianza y utilidad de memorias para RAG, agentes y operaciones.",
        "demo_allowed": True,
        "default_quota_monthly": 160,
    },
]

INTELLIGENCE_FEATURE_MAP = {item["key"]: item for item in INTELLIGENCE_FEATURES}

PREDICTION_FEATURE_MAP: dict[str, str] = {
    "lead_scoring": "lead_scoring_ml",
    "churn_prediction": "churn_prediction",
    "smart_remarketing": "smart_remarketing",
    "operational_anomaly": "ai_operational_intelligence",
    "campaign_optimization": "ml_predictions",
    "trigger_optimization": "ml_predictions",
    "advisor_insights": "ai_advisors_premium",
}
