from __future__ import annotations

from typing import Any


ECOSYSTEM_FEATURE_KEYS = [
    "ai_marketplace",
    "ai_plugin_center",
    "ai_developer_console",
    "ai_tool_registry",
    "ai_app_framework",
]

ECOSYSTEM_SCOPES = [
    "agents:read",
    "agents:install",
    "plugins:read",
    "plugins:write",
    "tools:read",
    "tools:write",
    "events:subscribe",
    "apps:read",
    "apps:write",
    "integrations:read",
    "integrations:write",
    "analytics:read",
]

ECOSYSTEM_EVENT_TYPES = [
    "lead.created",
    "lead.hot_detected",
    "churn.detected",
    "customer.inactive",
    "campaign.sent",
    "campaign.converted",
    "campaign.low_performance",
    "webhook.failed",
    "queue.degraded",
    "anomaly.detected",
    "ai.recommendation.generated",
    "ai.agent.installed",
    "ai.plugin.created",
    "ai.tool.registered",
]

DEFAULT_MARKETPLACE_ITEMS: list[dict[str, Any]] = [
    {
        "item_key": "agent.sales_closer.v1",
        "item_type": "agent_template",
        "category": "agent_store",
        "name": "Sales Closer Agent",
        "description": "Agent template for lead qualification, follow-up and sales closing assistance.",
        "required_feature_key": "ai_marketplace",
        "manifest_json": {"agent_type": "sales", "install_mode": "agent_template", "recommended_status": "draft"},
        "permissions_json": ["agents:install", "crm:read", "advisor:write"],
        "tags_json": ["sales", "crm", "agent"],
    },
    {
        "item_key": "agent.retention.v1",
        "item_type": "agent_template",
        "category": "agent_store",
        "name": "Retention Agent",
        "description": "Agent template for churn prevention, inactive customer recovery and retention playbooks.",
        "required_feature_key": "ai_marketplace",
        "manifest_json": {"agent_type": "retention", "install_mode": "agent_template", "recommended_status": "draft"},
        "permissions_json": ["agents:install", "crm:read", "intelligence:read"],
        "tags_json": ["retention", "churn", "agent"],
    },
    {
        "item_key": "workflow.churn_recovery.v1",
        "item_type": "workflow_template",
        "category": "workflows",
        "name": "Churn Recovery Workflow",
        "description": "Draft recovery workflow for inactive customers with approval-first remarketing recommendations.",
        "required_feature_key": "ai_app_framework",
        "manifest_json": {"workflow_type": "churn_recovery", "activation": "draft_only", "requires_preflight": True},
        "permissions_json": ["events:subscribe", "analytics:read", "apps:write"],
        "tags_json": ["workflow", "retention", "remarketing"],
    },
    {
        "item_key": "playbook.meta_health.v1",
        "item_type": "playbook",
        "category": "operations",
        "name": "Meta Health Playbook",
        "description": "Operational playbook for webhook drift, token health and subscribed_apps checks.",
        "required_feature_key": "ai_app_framework",
        "manifest_json": {"playbook_type": "meta_health", "risk_level": "medium", "side_effects": "approval_required"},
        "permissions_json": ["analytics:read", "events:subscribe"],
        "tags_json": ["meta", "operations", "self_healing"],
    },
    {
        "item_key": "automation.lead_prioritization.v1",
        "item_type": "automation",
        "category": "automation",
        "name": "Lead Prioritization Automation",
        "description": "Automation metadata pack for ranking hot leads and routing follow-up tasks.",
        "required_feature_key": "ai_tool_registry",
        "manifest_json": {"automation_type": "lead_prioritization", "execution": "recommendation_only"},
        "permissions_json": ["crm:read", "analytics:read", "advisor:write"],
        "tags_json": ["lead_scoring", "automation", "advisor"],
    },
    {
        "item_key": "ai_pack.restaurant_growth.v1",
        "item_type": "ai_pack",
        "category": "industry_packs",
        "name": "Restaurant Growth AI Pack",
        "description": "Industry pack for reservations, upsell, no-show recovery and menu-driven follow-ups.",
        "required_feature_key": "ai_marketplace",
        "manifest_json": {"industry_code": "restaurant", "resources": ["agents", "playbooks", "dashboards"]},
        "permissions_json": ["agents:install", "apps:write", "analytics:read"],
        "tags_json": ["restaurant", "vertical", "growth"],
    },
    {
        "item_key": "ai_app.operations_console.v1",
        "item_type": "ai_app",
        "category": "ai_apps",
        "name": "AI Operations Console",
        "description": "Mini app manifest for anomaly, recommendation and autonomous action dashboards.",
        "required_feature_key": "ai_app_framework",
        "manifest_json": {"app_type": "dashboard", "panels": ["anomalies", "actions", "recommendations"]},
        "permissions_json": ["apps:write", "analytics:read", "events:subscribe"],
        "tags_json": ["dashboard", "operations", "ai_app"],
    },
]

DEFAULT_TOOL_REGISTRY: list[dict[str, Any]] = [
    {
        "tool_key": "crm.search_contact",
        "name": "Search CRM Contact",
        "category": "crm",
        "description": "Read-only CRM contact lookup tool for agents and AI apps.",
        "risk_level": "low",
        "handler_ref": "app_saas.crm.read.search_contact",
        "permission_scopes_json": ["crm:read"],
        "input_schema_json": {"type": "object", "required": ["query"]},
    },
    {
        "tool_key": "crm.create_lead",
        "name": "Create Lead",
        "category": "crm",
        "description": "Approval-first lead creation tool metadata.",
        "risk_level": "medium",
        "handler_ref": "app_saas.crm.write.create_lead",
        "permission_scopes_json": ["crm:write"],
        "input_schema_json": {"type": "object", "required": ["name"]},
    },
    {
        "tool_key": "messaging.send_whatsapp",
        "name": "Send WhatsApp",
        "category": "messaging",
        "description": "High-risk outbound messaging tool metadata; execution requires existing dispatch controls.",
        "risk_level": "high",
        "handler_ref": "app_saas.workers.dispatch.enqueue_whatsapp",
        "permission_scopes_json": ["messaging:write", "approval:required"],
        "input_schema_json": {"type": "object", "required": ["conversation_id", "message"]},
    },
    {
        "tool_key": "analytics.query",
        "name": "Query Analytics",
        "category": "analytics",
        "description": "Read-only analytics query tool for advisors, dashboards and plugins.",
        "risk_level": "low",
        "handler_ref": "app_saas.intelligence.analytics.query",
        "permission_scopes_json": ["analytics:read"],
        "input_schema_json": {"type": "object", "required": ["metric"]},
    },
    {
        "tool_key": "workflow.trigger_run",
        "name": "Trigger Dry Run",
        "category": "workflow",
        "description": "Trigger simulation tool metadata for campaign/workflow optimization.",
        "risk_level": "medium",
        "handler_ref": "app_saas.campaigns.triggers.simulate",
        "permission_scopes_json": ["workflows:read", "approval:required"],
        "input_schema_json": {"type": "object", "required": ["sample_message"]},
    },
    {
        "tool_key": "knowledge.retrieve",
        "name": "Retrieve Knowledge",
        "category": "knowledge",
        "description": "Tenant-isolated RAG retrieval tool for agents and AI apps.",
        "risk_level": "low",
        "handler_ref": "app_saas.knowledge.retrieve",
        "permission_scopes_json": ["knowledge:read"],
        "input_schema_json": {"type": "object", "required": ["query"]},
    },
    {
        "tool_key": "observability.query_health",
        "name": "Query Health",
        "category": "observability",
        "description": "Read-only operational health tool for Operations Agent and AI apps.",
        "risk_level": "low",
        "handler_ref": "app_saas.observability.health_snapshot",
        "permission_scopes_json": ["observability:read"],
        "input_schema_json": {"type": "object", "required": ["scope"]},
    },
    {
        "tool_key": "advisor.create_action",
        "name": "Create Advisor Action",
        "category": "advisor",
        "description": "Approval-first action draft creation for AI recommendations.",
        "risk_level": "medium",
        "handler_ref": "app_saas.advisor.actions.create_draft",
        "permission_scopes_json": ["advisor:write", "approval:required"],
        "input_schema_json": {"type": "object", "required": ["title", "description"]},
    },
]
